/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user (mocked auth) */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's name or email */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's settings */
        get: operations["get_my_settings_api_me_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update settings
         * @description Partial update. Unknown fields and null values are rejected.
         */
        patch: operations["update_my_settings_api_me_settings_patch"];
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings */
        get: operations["list_meetings_api_meetings_get"];
        put?: never;
        /** Create a meeting */
        post: operations["create_meeting_api_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a meeting from a transcript file (.txt, .vtt or .json) */
        post: operations["upload_meeting_api_meetings_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete several meetings in one transaction
         * @description 404 (and nothing deleted) if any id does not exist; 422 for an empty list.
         */
        post: operations["bulk_delete_meetings_api_meetings_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meeting detail */
        get: operations["get_meeting_api_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        /** Delete a meeting */
        delete: operations["delete_meeting_api_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        /** Update title, date, participants, tags or privacy */
        patch: operations["update_meeting_api_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/meetings/{meeting_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the transcript */
        get: operations["get_transcript_api_meetings__meeting_id__transcript_get"];
        put?: never;
        /**
         * Attach a transcript to a meeting that has none
         * @description Multipart `file` (.txt/.vtt/.json) or JSON `{text}`. Starts processing. 409 if a transcript already exists.
         */
        post: operations["attach_transcript_api_meetings__meeting_id__transcript_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/summary/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate summary and chapters
         * @description Regenerates the overview, keywords and chapters. Action items are only generated if the meeting has none, so existing tasks are never overwritten.
         */
        post: operations["regenerate_summary_api_meetings__meeting_id__summary_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Smart Search insights: speaker stats, transcript filters and sentiment
         * @description Computed on read from the transcript with simple heuristics (regexes and a small sentiment lexicon).
         */
        get: operations["get_insights_api_meetings__meeting_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/transcript/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find and replace text in the transcript
         * @description Literal (not regex) match, case-insensitive unless `case_sensitive`. `replaced` counts occurrences. All-or-nothing: if any segment would become empty nothing is changed (422).
         */
        post: operations["replace_in_transcript_api_meetings__meeting_id__transcript_replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/speakers/reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move every segment of one speaker to another participant */
        post: operations["reassign_speaker_api_meetings__meeting_id__speakers_reassign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry processing of a failed meeting
         * @description 409 unless the meeting's status is `failed`. The meeting goes back to `processing`.
         */
        post: operations["retry_meeting_api_meetings__meeting_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the emails a meeting is shared with */
        get: operations["list_shares_api_meetings__meeting_id__shares_get"];
        put?: never;
        /**
         * Share a meeting with an email
         * @description Recorded only: no email is sent (auth is mocked). 409 if already shared with that email.
         */
        post: operations["create_share_api_meetings__meeting_id__shares_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Stop sharing with an email */
        delete: operations["delete_share_api_meetings__meeting_id__shares__share_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit a segment's text or speaker
         * @description Empty text is rejected (422). The speaker must be a participant of the meeting (422).
         */
        patch: operations["update_segment_api_segments__segment_id__patch"];
        trace?: never;
    };
    "/api/transcripts/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry-run parse of a transcript (nothing is saved)
         * @description Accepts a multipart `file` (.txt/.vtt/.json, max 5 MB) or JSON `{"text": ...}`. Returns the detected format, segment count, duration, speakers (with matches to existing people), the first segments and warnings. 415 unsupported extension, 413 too large, 422 empty or unparseable.
         */
        post: operations["parse_transcript_preview_api_transcripts_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List action items across all meetings */
        get: operations["list_action_items_api_action_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an action item to a meeting */
        post: operations["create_action_item_api_meetings__meeting_id__action_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/action-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an action item */
        delete: operations["delete_action_item_api_action_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update an action item */
        patch: operations["update_action_item_api_action_items__item_id__patch"];
        trace?: never;
    };
    "/api/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List people with meeting stats */
        get: operations["list_people_api_people_get"];
        put?: never;
        /** Create a person */
        post: operations["create_person_api_people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create a tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search all transcripts and meeting titles
         * @description Full-text search (SQLite FTS5) over every transcript, plus meeting titles. Input is sanitised, so punctuation and FTS operators are treated as plain text. Snippets are HTML-safe with matches wrapped in `<mark>`.
         */
        get: operations["global_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemCreate */
        ActionItemCreate: {
            /** Text */
            text: string;
            /** Assignee Id */
            assignee_id?: number | null;
            /** Source Segment Id */
            source_segment_id?: number | null;
            /**
             * Is Completed
             * @default false
             */
            is_completed: boolean;
            /** Due Date */
            due_date?: string | null;
        };
        /** ActionItemOut */
        ActionItemOut: {
            /** Id */
            id: number;
            /** Meeting Id */
            meeting_id: number;
            /** Text */
            text: string;
            assignee: components["schemas"]["PersonBrief"] | null;
            /** Source Segment Id */
            source_segment_id: number | null;
            /** Source Start Ms */
            source_start_ms: number | null;
            /** Is Completed */
            is_completed: boolean;
            /** Due Date */
            due_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ActionItemUpdate
         * @description Partial update: only fields present in the request body are changed (null clears nullable fields).
         */
        ActionItemUpdate: {
            /** Text */
            text?: string | null;
            /** Assignee Id */
            assignee_id?: number | null;
            /** Source Segment Id */
            source_segment_id?: number | null;
            /** Is Completed */
            is_completed?: boolean | null;
            /** Due Date */
            due_date?: string | null;
        };
        /**
         * ActionItemWithMeeting
         * @description An action item together with the meeting it came from (for the cross-meeting Tasks view).
         */
        ActionItemWithMeeting: {
            /** Id */
            id: number;
            /** Meeting Id */
            meeting_id: number;
            /** Text */
            text: string;
            assignee: components["schemas"]["PersonBrief"] | null;
            /** Source Segment Id */
            source_segment_id: number | null;
            /** Source Start Ms */
            source_start_ms: number | null;
            /** Is Completed */
            is_completed: boolean;
            /** Due Date */
            due_date: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Meeting Title */
            meeting_title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
        };
        /**
         * AutoJoin
         * @enum {string}
         */
        AutoJoin: "all" | "owned" | "teammates" | "invited";
        /** Body_upload_meeting_api_meetings_upload_post */
        Body_upload_meeting_api_meetings_upload_post: {
            /**
             * File
             * @description Transcript file: .txt, .vtt or .json
             */
            file: string;
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /** @default upload */
            platform: components["schemas"]["Platform"];
        };
        /** ChapterOut */
        ChapterOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Summary */
            summary: string | null;
            /** Order Index */
            order_index: number;
            /** Points */
            points: components["schemas"]["ChapterPoint"][];
        };
        /** ChapterPoint */
        ChapterPoint: {
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
        };
        /** FilterCategory */
        FilterCategory: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Segment Ids */
            segment_ids: number[];
        };
        /**
         * GeneratedBy
         * @enum {string}
         */
        GeneratedBy: "seed" | "heuristic" | "llm";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** MeetingBulkDelete */
        MeetingBulkDelete: {
            /** Ids */
            ids: number[];
        };
        /** MeetingBulkDeleteResult */
        MeetingBulkDeleteResult: {
            /** Deleted */
            deleted: number;
        };
        /** MeetingCreate */
        MeetingCreate: {
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /**
             * Participants
             * @description Participant names; existing people are reused
             */
            participants?: string[];
            /**
             * Participant Ids
             * @description Existing people to add as participants
             */
            participant_ids?: number[];
            /** Tag Ids */
            tag_ids?: number[];
            /**
             * Duration Seconds
             * @description Used when there is no transcript
             */
            duration_seconds?: number | null;
            /** @default upload */
            platform: components["schemas"]["Platform"];
            /**
             * Transcript Text
             * @description Pasted transcript (.txt, .vtt or .json content; the format is detected)
             */
            transcript_text?: string | null;
        };
        /** MeetingDetail */
        MeetingDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /** Duration Seconds */
            duration_seconds: number;
            platform: components["schemas"]["Platform"];
            status: components["schemas"]["MeetingStatus"];
            /** Media Url */
            media_url: string | null;
            /** Error Message */
            error_message: string | null;
            /** Processed At */
            processed_at: string | null;
            privacy: components["schemas"]["Privacy"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Participants */
            participants: components["schemas"]["ParticipantOut"][];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            summary: components["schemas"]["SummaryOut"] | null;
            /** Chapters */
            chapters: components["schemas"]["ChapterOut"][];
            /** Action Items */
            action_items: components["schemas"]["ActionItemOut"][];
        };
        /** MeetingInsights */
        MeetingInsights: {
            /** Speakers */
            speakers: components["schemas"]["SpeakerInsight"][];
            /** Filters */
            filters: components["schemas"]["FilterCategory"][];
            sentiment: components["schemas"]["SentimentSummary"];
        };
        /** MeetingListItem */
        MeetingListItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /** Duration Seconds */
            duration_seconds: number;
            platform: components["schemas"]["Platform"];
            status: components["schemas"]["MeetingStatus"];
            /** Error Message */
            error_message: string | null;
            /** Processed At */
            processed_at: string | null;
            /** Participants */
            participants: components["schemas"]["PersonBrief"][];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Action Item Count */
            action_item_count: number;
            /** Open Action Item Count */
            open_action_item_count: number;
            /** Summary Bullets */
            summary_bullets: components["schemas"]["SummaryBullet"][];
        };
        /** MeetingPage */
        MeetingPage: {
            /** Items */
            items: components["schemas"]["MeetingListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * MeetingStatus
         * @enum {string}
         */
        MeetingStatus: "processing" | "ready" | "failed";
        /**
         * MeetingUpdate
         * @description Partial update; participant_ids and tag_ids, when present, replace the current sets.
         */
        MeetingUpdate: {
            /** Title */
            title?: string | null;
            /** Meeting Date */
            meeting_date?: string | null;
            /** Participant Ids */
            participant_ids?: number[] | null;
            /** Tag Ids */
            tag_ids?: number[] | null;
            privacy?: components["schemas"]["Privacy"] | null;
        };
        /** ParsePreview */
        ParsePreview: {
            /** Format Detected */
            format_detected: string;
            /** Segment Count */
            segment_count: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Speakers */
            speakers: components["schemas"]["SpeakerPreview"][];
            /** Preview */
            preview: components["schemas"]["SegmentPreview"][];
            /** Warnings */
            warnings: string[];
        };
        /** ParticipantOut */
        ParticipantOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Avatar Color */
            avatar_color: string;
            /** Email */
            email: string | null;
            role: components["schemas"]["ParticipantRole"];
        };
        /**
         * ParticipantRole
         * @enum {string}
         */
        ParticipantRole: "host" | "attendee";
        /** PersonBrief */
        PersonBrief: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Avatar Color */
            avatar_color: string;
        };
        /** PersonCreate */
        PersonCreate: {
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Avatar Color */
            avatar_color?: string | null;
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Avatar Color */
            avatar_color: string;
            /** Email */
            email: string | null;
        };
        /** PersonWithStats */
        PersonWithStats: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Avatar Color */
            avatar_color: string;
            /** Email */
            email: string | null;
            /** Meeting Count */
            meeting_count: number;
            /** Last Meeting Date */
            last_meeting_date: string | null;
        };
        /**
         * Platform
         * @enum {string}
         */
        Platform: "zoom" | "google_meet" | "teams" | "upload";
        /**
         * Privacy
         * @description Who may open the meeting. Recorded and editable, but not enforced (auth is mocked).
         * @enum {string}
         */
        Privacy: "link" | "teammates_participants" | "teammates" | "participants" | "participants_team" | "owner";
        /** ReassignRequest */
        ReassignRequest: {
            /** From Person Id */
            from_person_id: number;
            /** To Person Id */
            to_person_id: number;
        };
        /** ReassignResult */
        ReassignResult: {
            /** Reassigned */
            reassigned: number;
        };
        /**
         * RecapRecipients
         * @enum {string}
         */
        RecapRecipients: "everyone" | "team" | "me";
        /** ReplaceRequest */
        ReplaceRequest: {
            /** Find */
            find: string;
            /** Replace */
            replace: string;
            /**
             * Case Sensitive
             * @default false
             */
            case_sensitive: boolean;
            /**
             * Segment Ids
             * @description Limit the replacement to these segments
             */
            segment_ids?: number[] | null;
        };
        /** ReplaceResult */
        ReplaceResult: {
            /** Replaced */
            replaced: number;
            /** Segment Ids */
            segment_ids: number[];
        };
        /** SearchMatch */
        SearchMatch: {
            /** Segment Id */
            segment_id: number;
            /** Start Ms */
            start_ms: number;
            speaker: components["schemas"]["PersonBrief"];
            /** Snippet */
            snippet: string;
        };
        /** SearchMeeting */
        SearchMeeting: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            platform: components["schemas"]["Platform"];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Total Meetings */
            total_meetings: number;
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            meeting: components["schemas"]["SearchMeeting"];
            /** Title Match */
            title_match: boolean;
            /** Match Count */
            match_count: number;
            /** Matches */
            matches: components["schemas"]["SearchMatch"][];
        };
        /** SegmentOut */
        SegmentOut: {
            /** Id */
            id: number;
            /** Sequence Index */
            sequence_index: number;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
            speaker: components["schemas"]["PersonBrief"];
        };
        /** SegmentPreview */
        SegmentPreview: {
            /** Speaker */
            speaker: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
        };
        /** SegmentSentiment */
        SegmentSentiment: {
            /** Segment Id */
            segment_id: number;
            /** Label */
            label: string;
            /** Score */
            score: number;
        };
        /**
         * SegmentUpdate
         * @description Partial update of one segment. Timings are never edited.
         */
        SegmentUpdate: {
            /** Text */
            text?: string | null;
            /** Speaker Id */
            speaker_id?: number | null;
        };
        /** SentimentSummary */
        SentimentSummary: {
            /** Positive Pct */
            positive_pct: number;
            /** Neutral Pct */
            neutral_pct: number;
            /** Negative Pct */
            negative_pct: number;
            /** By Segment */
            by_segment: components["schemas"]["SegmentSentiment"][];
        };
        /** ShareCreate */
        ShareCreate: {
            /** Email */
            email: string;
        };
        /** ShareOut */
        ShareOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SpeakerInsight */
        SpeakerInsight: {
            person: components["schemas"]["PersonBrief"];
            /** Talk Time Ms */
            talk_time_ms: number;
            /** Talk Time Pct */
            talk_time_pct: number;
            /** Wpm */
            wpm: number;
            /** Segment Count */
            segment_count: number;
        };
        /** SpeakerPreview */
        SpeakerPreview: {
            /** Name */
            name: string;
            /** Matched Person Id */
            matched_person_id: number | null;
        };
        /** SummaryBullet */
        SummaryBullet: {
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Overview */
            overview: string;
            /** Keywords */
            keywords: string[];
            /** Bullets */
            bullets: components["schemas"]["SummaryBullet"][];
            generated_by: components["schemas"]["GeneratedBy"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TagCreate */
        TagCreate: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /**
         * Theme
         * @enum {string}
         */
        Theme: "light" | "dark" | "system";
        /** TranscriptOut */
        TranscriptOut: {
            /** Meeting Id */
            meeting_id: number;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Matching Segment Ids */
            matching_segment_ids?: number[] | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Avatar Url */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserSettingsOut */
        UserSettingsOut: {
            default_privacy: components["schemas"]["Privacy"];
            auto_join: components["schemas"]["AutoJoin"];
            recap_recipients: components["schemas"]["RecapRecipients"];
            /** Language */
            language: string;
            /** Email Notes Enabled */
            email_notes_enabled: boolean;
            /** Notify On Ready */
            notify_on_ready: boolean;
            theme: components["schemas"]["Theme"];
        };
        /**
         * UserSettingsUpdate
         * @description Partial update: only the fields present are changed. null is not a valid value for any field.
         */
        UserSettingsUpdate: {
            default_privacy?: components["schemas"]["Privacy"] | null;
            auto_join?: components["schemas"]["AutoJoin"] | null;
            recap_recipients?: components["schemas"]["RecapRecipients"] | null;
            /** Language */
            language?: string | null;
            /** Email Notes Enabled */
            email_notes_enabled?: boolean | null;
            /** Notify On Ready */
            notify_on_ready?: boolean | null;
            theme?: components["schemas"]["Theme"] | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_settings_api_me_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsOut"];
                };
            };
        };
    };
    update_my_settings_api_me_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meetings_api_meetings_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive title search */
                q?: string | null;
                participant_id?: number | null;
                /** @description Repeatable; a meeting matches if it has ANY of the given tags */
                tag_id?: number[] | null;
                /** @description Inclusive, UTC */
                date_from?: string | null;
                /** @description Inclusive, UTC */
                date_to?: string | null;
                status?: components["schemas"]["MeetingStatus"] | null;
                platform?: components["schemas"]["Platform"] | null;
                /** @description Minimum duration in seconds (inclusive) */
                min_duration?: number | null;
                /** @description Maximum duration in seconds (inclusive) */
                max_duration?: number | null;
                /** @description Only meetings whose processing finished at or after this time */
                processed_since?: string | null;
                sort?: "recent" | "oldest";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meeting_api_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_meeting_api_meetings_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_meeting_api_meetings_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_meetings_api_meetings_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingBulkDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingBulkDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_api_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meeting_api_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_meetings__meeting_id__transcript_get: {
        parameters: {
            query?: {
                /** @description If set, matching_segment_ids lists segments matching this text */
                q?: string | null;
            };
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_transcript_api_meetings__meeting_id__transcript_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_summary_api_meetings__meeting_id__summary_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_api_meetings__meeting_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingInsights"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_in_transcript_api_meetings__meeting_id__transcript_replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_speaker_api_meetings__meeting_id__speakers_reassign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReassignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReassignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_meeting_api_meetings__meeting_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shares_api_meetings__meeting_id__shares_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_api_meetings__meeting_id__shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_share_api_meetings__meeting_id__shares__share_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
                share_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_segment_api_segments__segment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_transcript_preview_api_transcripts_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsePreview"];
                };
            };
        };
    };
    list_action_items_api_action_items_get: {
        parameters: {
            query?: {
                /** @description Only completed (true) or open (false) items */
                completed?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemWithMeeting"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_action_item_api_meetings__meeting_id__action_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_action_item_api_action_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_action_item_api_action_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_people_api_people_get: {
        parameters: {
            query?: {
                /** @description Filter by name */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_person_api_people_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_search_api_search_get: {
        parameters: {
            query: {
                q: string;
                /** @description Max meetings returned */
                limit?: number;
                matches_per_meeting?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
